# Permalinks
plugins: [jekyll-paginate]
gems:
  - jekyll-pagination
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Setup
title: yonghyun, 기록
baseurl: ""
url: "https://yoncho.github.io"

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# About
author:
  name: Yonghyun
  url: https://yoncho.github.io/
  email: yoncho@student.42seoul.kr
  github: yoncho
  google_analytics: 

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/yoncho/yoncho.github.io
